[deploy]
healthcheckPath = "/api/v1/health/"
healthcheckTimeout = 300
startCommand = "gunicorn census_portal.wsgi --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
