# Generated by Django 6.0.1 on 2026-02-08 05:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pincode', models.CharField(db_index=True, max_length=10)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('building_number', models.CharField(blank=True, max_length=50)),
                ('floor_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEMOLISHED', 'Demolished'), ('NEW', 'New Structure'), ('MODIFIED', 'Modified')], default='ACTIVE', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.zone')),
            ],
            options={
                'db_table': 'master_addresses',
                'ordering': ['pincode', 'address_line1'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('FLAGGED', 'Flagged')], default='DRAFT', max_length=20)),
                ('pincode', models.CharField(max_length=10)),
                ('address_line', models.TextField()),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('location_warning', models.BooleanField(default=False)),
                ('head_name', models.CharField(max_length=255)),
                ('head_gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('head_age', models.PositiveIntegerField()),
                ('head_phone', models.CharField(blank=True, max_length=15)),
                ('head_aadhar', models.CharField(blank=True, max_length=12)),
                ('head_occupation', models.CharField(blank=True, max_length=100)),
                ('head_education', models.CharField(blank=True, max_length=100)),
                ('total_members', models.PositiveIntegerField(default=1)),
                ('male_members', models.PositiveIntegerField(default=0)),
                ('female_members', models.PositiveIntegerField(default=0)),
                ('other_members', models.PositiveIntegerField(default=0)),
                ('children_under_5', models.PositiveIntegerField(default=0)),
                ('children_5_to_18', models.PositiveIntegerField(default=0)),
                ('senior_citizens', models.PositiveIntegerField(default=0)),
                ('annual_income', models.CharField(blank=True, max_length=50)),
                ('ration_card_type', models.CharField(blank=True, max_length=50)),
                ('owns_vehicle', models.BooleanField(default=False)),
                ('vehicle_type', models.CharField(blank=True, max_length=50)),
                ('ownership_type', models.CharField(blank=True, max_length=50)),
                ('house_type', models.CharField(blank=True, max_length=50)),
                ('rooms_count', models.PositiveIntegerField(default=1)),
                ('has_electricity', models.BooleanField(default=True)),
                ('has_water_connection', models.BooleanField(default=False)),
                ('has_toilet', models.BooleanField(default=False)),
                ('has_lpg', models.BooleanField(default=False)),
                ('schemes_availed', models.JSONField(blank=True, default=list)),
                ('family_members', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('audit_trail', models.JSONField(blank=True, default=list)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='surveys.masteraddress')),
                ('surveyor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surveys', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_surveys', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surveys', to='accounts.zone')),
            ],
            options={
                'db_table': 'survey_responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('surveys_completed', models.PositiveIntegerField(default=0)),
                ('target', models.PositiveIntegerField()),
                ('surveyor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_progress',
                'ordering': ['-date'],
                'unique_together': {('surveyor', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='masteraddress',
            index=models.Index(fields=['pincode'], name='master_addr_pincode_ed53bd_idx'),
        ),
        migrations.AddIndex(
            model_name='masteraddress',
            index=models.Index(fields=['zone', 'pincode'], name='master_addr_zone_id_86fdf0_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['surveyor'], name='survey_resp_surveyo_11338d_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['zone'], name='survey_resp_zone_id_4ca44c_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['status'], name='survey_resp_status_e3e571_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['submitted_at'], name='survey_resp_submitt_c31738_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['pincode'], name='survey_resp_pincode_b61965_idx'),
        ),
    ]
